name: .NET Build

on: 
  push: 
    branches: 
      - master
  pull_request:

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Setup .NET 10
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
      with:
        dotnet-version: 10.x
    - name: Build JavaToCSharp
      run: dotnet build ./JavaToCSharp/JavaToCSharp.csproj --configuration Release

    - name: Test JavaToCSharp.Tests
      run: dotnet test ./JavaToCSharp.Tests/JavaToCSharp.Tests.csproj --configuration Release

    - name: Build JavaToCSharpCli
      run: dotnet build ./JavaToCSharpCli/JavaToCSharpCli.csproj --configuration Release

    - name: Build JavaToCSharpGui
      run: dotnet build ./JavaToCSharpGui/JavaToCSharpGui.csproj --configuration Release
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Setup .NET 10
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
      with:
        dotnet-version: 10.x
    - name: Build JavaToCSharp
      run: dotnet build ./JavaToCSharp/JavaToCSharp.csproj --configuration Release

    - name: Test JavaToCSharp.Tests
      run: dotnet test ./JavaToCSharp.Tests/JavaToCSharp.Tests.csproj --configuration Release

    - name: Build JavaToCSharpCli
      run: dotnet build ./JavaToCSharpCli/JavaToCSharpCli.csproj --configuration Release

    - name: Build JavaToCSharpGui
      run: dotnet build ./JavaToCSharpGui/JavaToCSharpGui.csproj --configuration Release
